services:
  cordova:
    build: .
    volumes:
        - ./wwwapp:/app/www
        - ./config.xml:/app/config.xml
        - ./apks:/app/platforms/android/app/build/outputs/apk
        - ./entrypoint.sh:/entrypoint.sh:ro
    ports:
        - "8122:8000"
    entrypoint: ["/bin/bash", "/entrypoint.sh"]